Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/SymbolArray:
  Exclude:
    - 'Gemfile'

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'config/initializers/wrap_parameters.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/seeds.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
