env:
  global:
  - CC_TEST_REPORTER_ID=87b67e9610702652e76b79e0c0d65b9d5e940165fb7b1621efaff1c79eb45dcb
language: ruby
rvm:
- 2.5.0
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
- bundle exec rubocop
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: znpsOGxQ5ro2QQ72BPMV1vKSCs1EVjJeNOpeNgCzpJ7AelFak79AQNuWXb8622JFLpd5sQtyZF/i0tUKs17UGEm/lE54hwhIPq9XU4oqpt1SVZV0bWFBgUvCEhqr8TyPL1MD2rKFnG4MCbZH1greS1TxOOwIA8smdy1d2uqZchjfUctS1NJaTSaYDo4Rs+vC2XW3E/aqZOWnwabE1VFy8mUWCDQMcRS+EF9PvCsRJbPZvEcPqA+pYYihCY1Ah8c3jdt+jnR8zw9DkUOiMDC5vRmYbkEuj6F43VQ/+wK02WBKRk+Inh2UZSSrJ8o89exppavYVdi6PB0V7crQStrI/MXo2Z6Vo47rkZQP0hJF7Uedwjal0jbIcXszzkcufzXW8xj2pvB7xeODeWl0S43fSC28zj3oa4gjDMaEDBoG23aZk1dzp2Jn1z1iEpBCH3+y1nkLdkMci0zte1MnF4QCbmH9gQuORGpXCs6y7gmjlSHCHSddUIJZH+1wLsGiSNinAqVcWUf8ElsSXVJTcL6zQQzImsZSBFCatuWxZ37thie93O+vvcB5rtAxeGD/5hN7ggz9TKL2tcxU69RWdiSmbacJWDccAfO7ozwvuzOhyxF8NeUonLQ4EU9w8n1ZhJykIZwOzF9B/VWhpaUWm6qN5Tj4q6EXFYAvVeK52IYnGQY=
  app: acebook-team-rocket
  on:
    repo: Sindex42/acebook-team-rocket
