env:
  global:
  - CC_TEST_REPORTER_ID=87b67e9610702652e76b79e0c0d65b9d5e940165fb7b1621efaff1c79eb45dcb
language: ruby
rvm:
- 2.5.0
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
- bundle exec rubocop
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: IT6C6hb0FdbiJAW+wKj5aBna+LyWNvfU5fYAjfPmBYNGR4NdyqyYLC8Fq99dtu2gKz6jiJ64Ylk8ppF//xESI5t9vn6j9e/lZuBc8dq2vGvunaCzI/GnuQVS48JrKn+MDOmUGVfLDLVTC5mALhdaeFovb6GVKuSSlucwsNBAjwwXSuOb6oYdw7UzVW04h1igYqvfwbJJMkzz0r4jetLlBCyYdhBkUEVO8ZjPMzPmglW8poflW2ugaoWHizcfOESsNFc9nJLiv1S3Zo2RyiD9mNolC5igY0wWaUmAP1EwllQdgSkdthotcRKuC6i+Gh6wPiUf/40cQhNWqMyt0QiMzJ1T6mvoZo55F3HwgiKDG/TX+G4SNpDbGtdZ8E7Ug+b+TD9EE2ThVivJim0IVN7L/Qt8JI/wSt/2pd59yR3DA5zfqWTpQcGcnYJ0w9UTvFIi9xi2U9yMIe4VfCM6zgSlXoe7aEQjbeexjhws0PHnEpnOLr9OrSuZt3PxXbgMgdttWPtpE2Yv2QWhdeWxDRIvjLxyKDB/86uvhNa53MS+1tGwKGQ5wZC4koVdLjrw13hC2xjS9l0/S2kgQgz6M6S8tuI2rRbOrbQfZFLS2f2u9VRaejzboJC9muX9KpUaTYNsQDOnK1jLBYOASCMw8mkegsKetw95JsHFrpJZZf9X4Ig=
  run: "rake db:migrate"
  app: acebook-team-rocket
  on:
    repo: Sindex42/acebook-team-rocket
